package fr.utc.miage.sporttrack.entity.user.communication;

import fr.utc.miage.sporttrack.entity.enumeration.NotificationType;
import fr.utc.miage.sporttrack.entity.user.Athlete;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;

import java.time.LocalDateTime;

/**
 * JPA entity representing an in-app notification delivered to an athlete
 * within the SportTrack application.
 *
 * <p>Notifications are generated by various system events (e.g., message
 * received, friendship request, badge earned) and are addressed to a specific
 * recipient. An optional actor identifies the user who triggered the event.
 * Each notification includes a title, content, an optional target URL for
 * navigation, and a read/seen flag.</p>
 *
 * @author SportTrack Team
 */
@Entity
@Table(name = "notifications")
public class Notification {

    /** The unique database-generated identifier for this notification. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;

    /** The athlete to whom this notification is addressed. */
    @ManyToOne(optional = false)
    @JoinColumn(name = "recipient_id", nullable = false)
    private Athlete recipient;

    /** The athlete who triggered the event that caused this notification (optional). */
    @ManyToOne
    @JoinColumn(name = "actor_id")
    private Athlete actor;

    /** The category of this notification, indicating the type of event. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NotificationType type;

    /** The short title summarising this notification. */
    @Column(nullable = false)
    private String title;

    /** The detailed content or body of this notification. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    /** An optional URL to which the user should be redirected when clicking the notification. */
    @Column(name = "target_url")
    private String targetUrl;

    /** Indicates whether the recipient has already viewed this notification. */
    @Column(nullable = false)
    private boolean seen;

    /** The timestamp at which this notification was created. */
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    /**
     * No-argument constructor required by JPA.
     */
    public Notification() {
        // Required by JPA
    }

    /**
     * Returns the unique identifier of this notification.
     *
     * @return the notification's database identifier
     */
    public Integer getId() {
        return id;
    }

    /**
     * Returns the athlete to whom this notification is addressed.
     *
     * @return the recipient {@link Athlete}
     */
    public Athlete getRecipient() {
        return recipient;
    }

    /**
     * Returns the athlete who triggered this notification.
     *
     * @return the actor {@link Athlete}, or {@code null} if system-generated
     */
    public Athlete getActor() {
        return actor;
    }

    /**
     * Returns the type of this notification.
     *
     * @return the {@link NotificationType}
     */
    public NotificationType getType() {
        return type;
    }

    /**
     * Returns the title of this notification.
     *
     * @return the notification title
     */
    public String getTitle() {
        return title;
    }

    /**
     * Returns the content of this notification.
     *
     * @return the notification body text
     */
    public String getContent() {
        return content;
    }

    /**
     * Returns the target URL associated with this notification.
     *
     * @return the target URL, or {@code null} if none is defined
     */
    public String getTargetUrl() {
        return targetUrl;
    }

    /**
     * Returns whether this notification has been viewed by the recipient.
     *
     * @return {@code true} if seen, {@code false} otherwise
     */
    public boolean isSeen() {
        return seen;
    }

    /**
     * Returns the creation timestamp of this notification.
     *
     * @return the creation timestamp
     */
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the unique identifier of this notification.
     *
     * @param id the database identifier to assign
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * Sets the athlete to whom this notification is addressed.
     *
     * @param recipient the recipient {@link Athlete} to assign
     */
    public void setRecipient(Athlete recipient) {
        this.recipient = recipient;
    }

    /**
     * Sets the athlete who triggered this notification.
     *
     * @param actor the actor {@link Athlete} to assign
     */
    public void setActor(Athlete actor) {
        this.actor = actor;
    }

    /**
     * Sets the type of this notification.
     *
     * @param type the {@link NotificationType} to assign
     */
    public void setType(NotificationType type) {
        this.type = type;
    }

    /**
     * Sets the title of this notification.
     *
     * @param title the title to assign
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * Sets the content of this notification.
     *
     * @param content the body text to assign
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * Sets the target URL associated with this notification.
     *
     * @param targetUrl the target URL to assign
     */
    public void setTargetUrl(String targetUrl) {
        this.targetUrl = targetUrl;
    }

    /**
     * Sets whether this notification has been viewed by the recipient.
     *
     * @param seen {@code true} to mark as seen, {@code false} otherwise
     */
    public void setSeen(boolean seen) {
        this.seen = seen;
    }

    /**
     * Sets the creation timestamp of this notification.
     *
     * @param createdAt the creation timestamp to assign
     */
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Lifecycle callback that sets the creation timestamp to the current time
     * if not already provided, before the entity is first persisted.
     */
    @PrePersist
    public void onCreate() {
        if (createdAt == null) {
            createdAt = LocalDateTime.now();
        }
    }
}