spring.application.name=sporttrack


# Datasource (SQLite)
spring.datasource.url=jdbc:sqlite:./data/db/sporttrack.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
